author:
  image: nicolasbarbe/magnolia-base-debug
  ports:
    - "3000:8080"
    - "3001:1099"
    - "3002:1043"
  environment:
    - INSTANCE_TYPE=author_derby
    - MAGNOLIA_HOME=/var/data
  volumes:
    - ./quickstart-webapp/target/quickstart-webapp-1.0-SNAPSHOT:/var/lib/tomcat7/webapps/ROOT
    - ~/data/quickstart-project:/var/data
    - .:/var/src


# public:
#   build: .
#   command: run
#   ports:
#     - "3001:8080"
#   environment:
#     - INSTANCE_TYPE=public_derby
# public:
#   build: .
#   command: run
#   ports:
#     - "3001:8080"
#   environment:
#     - INSTANCE_TYPE=public_derby