author:
  image: nicolasbarbe/magnolia-base
  command: run
  ports:
    - "3000:8080"
  environment:
    - INSTANCE_TYPE=author_derby
  volumes:
    - ./quickstart-webapp/target/quickstart-webapp-1.0-SNAPSHOT:/var/lib/tomcat7/webapps/ROOT

# public:
#   build: .
#   command: run
#   ports:
#     - "3001:8080"
#   environment:
#     - INSTANCE_TYPE=public_derby